  version: "2"
  services:
    cbrpoc:
      container_name: cbrpoccont
      build:
        context: .
        dockerfile: ./Dockerfile
      links:
        - activemq:activemq
      volumes:
        - /myvolume:/var/myvolume
      ports:
        - "8085:8085"
      
    activemq:
      container_name: activemq
      image: webcenter/activemq
      environment:
        ACTIVEMQ_CONFIG_NAME: amqp-srv1
        ACTIVEMQ_CONFIG_DEFAULTACCOUNT: "false"
        ACTIVEMQ_ADMIN_LOGIN: admin
        ACTIVEMQ_ADMIN_PASSWORD: admin
        ACTIVEMQ_CONFIG_MINMEMORY: "1024"
        ACTIVEMQ_CONFIG_MAXMEMORY: "4096"
      volumes:
        - /data/activemq:/data
        - /var/log/activemq:/var/log/activemq
      ports:
        - "8161:8161"
        - "61616:61616"
        - "61613:61613"





